language: csharp
mono: none
services:
  - docker

jobs:
  include:
    - stage: "Build"
      script: docker build -t denstorti/testmvc:1.0.0 .
        - docker run -d -p 5000:80 denstorti/testmvc:1.0.0 
        - docker ps -a
        - VERSION=1.0.$TRAVIS_BUILD_NUMBER
        - echo VERSION $VERSION
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - docker tag testmvc denstorti/testmvc:$VERSION
        - docker push denstorti/testmvc:$VERSION
        - git tag $VERSION
        - git push origin --tags
        


        
