language: csharp
mono: none
services:
  - docker

jobs:
  include:
    - stage: "Build"
      script: docker build -t denstorti/testmvc:1.0.0 .
    
    - stage: "Run"
      script: 
        - docker run -d -p 5000:80 denstorti/testmvc:1.0.0 
        - docker ps -a
        - curl --write-out "%{http_code}\n" --silent --output /dev/null "http://localhost:5000"

    - stage: "Publish image"
      script: 
        - VERSION=1.0.$TRAVIS_BUILD_NUMBER
        - echo VERSION $VERSION
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push denstorti/testmvc:$VERSION

    - stage: "Git tagging"
      script: 
        - git tag $VERSION
        - git push origin --tags
        


        
