language: csharp
mono: none
services:
  - docker

jobs:
  include:
    - stage: "Build"
      script: docker build -t denstorti/testmvc:1.0.0 .
    
    - stage: "Run"
      script: 
        - docker run -d -p 5000:4567 denstorti/testmvc:1.0.0 
        - docker ps -a
