language: csharp
mono: none
services:
  - docker

before_install:
  - docker build -t denstorti/testmvc:1.0.0 .

script:
  - docker run -d -p 5000:4567 denstorti/testmvc:1.0.0 

after_script:
  - docker ps -a
